# Generated by Django 3.1 on 2025-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('PayPal', 'PayPal'), ('Stripe', 'Stripe')], max_length=100),
        ),
    ]
